Repository prography/pg-homepage-backend, pull requests merged in 2022-11, with the labels that each got.

#28 Fix: Add password & jwt env value
  .github/workflows/deploy.yml
Labels: bug

#29 hotfix env수정
  .github/workflows/deploy.yml
Labels: bug

#22 feat: pr 생성시 자동으로 author 생성 action추가
  .github/workflows/auto-author-assign.yml
Labels: documentation, enhancement

#24 Feat/part and quesiton dto
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/modules/api.module.ts
  src/modules/application/application.controller.ts
  src/modules/application/application.module.ts
  src/modules/application/application.service.ts
  src/modules/application/dto/create-application.dto.ts
  src/modules/application/dto/response-application.dto.ts
  src/modules/application/dto/update-application.dto.ts
  src/modules/part/dto/create-part.dto.ts
  src/modules/part/dto/put-part.dto.ts
  src/modules/part/dto/response-part.dto.ts
  src/modules/part/part.controller.ts
  src/modules/part/part.module.ts
  src/modules/part/part.service.spec.ts
  src/modules/part/part.service.ts
  src/modules/question/dto/create-question.dto.ts
  src/modules/question/dto/put-question.dto.ts
  src/modules/question/dto/response-question.dto.ts
  src/modules/question/question.controller.ts
  src/modules/question/question.module.ts
  src/modules/question/question.service.spec.ts
  src/modules/question/question.service.ts
  src/modules/user/dto/create-user.dto.ts
  src/modules/user/dto/put-user.dto.ts
  src/modules/user/dto/response-user.dto.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.module.ts
  src/modules/user/user.service.spec.ts
  src/modules/user/user.service.ts
Labels: enhancement

#30 배포
  .github/workflows/auto-author-assign.yml
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/modules/api.module.ts
  src/modules/application/application.controller.ts
  src/modules/application/application.module.ts
  src/modules/application/application.service.ts
  src/modules/application/dto/create-application.dto.ts
  src/modules/application/dto/response-application.dto.ts
  src/modules/application/dto/update-application.dto.ts
  src/modules/part/dto/create-part.dto.ts
  src/modules/part/dto/put-part.dto.ts
  src/modules/part/dto/response-part.dto.ts
  src/modules/part/part.controller.ts
  src/modules/part/part.module.ts
  src/modules/part/part.service.spec.ts
  src/modules/part/part.service.ts
  src/modules/question/dto/create-question.dto.ts
  src/modules/question/dto/put-question.dto.ts
  src/modules/question/dto/response-question.dto.ts
  src/modules/question/question.controller.ts
  src/modules/question/question.module.ts
  src/modules/question/question.service.spec.ts
  src/modules/question/question.service.ts
  src/modules/user/dto/create-user.dto.ts
  src/modules/user/dto/put-user.dto.ts
  src/modules/user/dto/response-user.dto.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.module.ts
  src/modules/user/user.service.spec.ts
  src/modules/user/user.service.ts
Labels: enhancement

#32 Feature/portfolio
  .env.sample
  .github/workflows/deploy.yml
  package.json
  src/core/swagger/swagger.type.ts
  src/infra/entity/Portpolios.entity.ts
  src/modules/api.module.ts
  src/modules/aws/aws.module.ts
  src/modules/aws/repository/aws.repository.ts
  src/modules/common/exception-filter/all-exceptions.filter.ts
  src/modules/generation/generation.module.ts
  src/modules/portfolio/controller/portfolio.controller.ts
  src/modules/portfolio/dto/create-portfolio.dto.ts
  src/modules/portfolio/dto/reponse-portfolio.dto.ts
  src/modules/portfolio/dto/update-portfolio.dto.ts
  src/modules/portfolio/portfolio.module.ts
  src/modules/portfolio/repository/portfolio.repository.ts
  src/modules/portfolio/service/portfolio.service.ts
Labels: enhancement

#35 Feature/34
  src/core/swagger/swagger.setup.ts
  src/modules/aws/repository/aws.repository.ts
  src/modules/generation/controller/generation.controller.ts
  src/modules/portfolio/controller/portfolio.controller.ts
Labels: bug

#36 Merge pull request #35 from prography/Feature/34
  src/core/swagger/swagger.setup.ts
  src/modules/aws/repository/aws.repository.ts
  src/modules/generation/controller/generation.controller.ts
  src/modules/portfolio/controller/portfolio.controller.ts
Labels: bug

#37 style: AccessKey 오타 수정
  .github/workflows/deploy.yml
Labels: bug

#44 현재 기수 반환 문제 해결
  src/modules/common/exception-filter/all-exceptions.filter.ts
  src/modules/generation/controller/generation.controller.ts
  src/modules/generation/service/generation.service.ts
Labels: bug

#50 role based로 인증 시스템 변경, 최종 완료 여부 확인하는 커럼 추가
  src/infra/entity/Answers.entity.ts
  src/infra/entity/Applications.entity.ts
  src/infra/entity/Generations.entity.ts
  src/infra/entity/Parts.entity.ts
  src/infra/entity/Portpolios.entity.ts
  src/infra/entity/Questions.entity.ts
  src/infra/entity/SelectOptions.entity.ts
  src/infra/entity/Users.entity.ts
  src/modules/application/application-base.module.ts
  src/modules/application/application.module.ts
  src/modules/application/controller/application.controller.ts
  src/modules/application/repository/application.repository.ts
  src/modules/application/service/application-admin.service.ts
  src/modules/application/service/application-base.service.ts
  src/modules/application/service/application.service.ts
  src/modules/application/service/index.ts
  src/modules/auth/Auth.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/role/roles.decorator.ts
  src/modules/auth/role/roles.enum.ts
  src/modules/auth/role/roles.guard.ts
  src/modules/auth/role/rolesType.ts
  src/modules/auth/service/auth.service.ts
  src/modules/generation/controller/generation.controller.ts
  src/modules/generation/generation.module.ts
  src/modules/part/controller/part.controller.ts
  src/modules/portfolio/controller/portfolio.controller.ts
  src/modules/question/controller/question.controller.ts
  src/modules/user/controller/user.controller.ts
  src/modules/user/service/index.ts
  src/modules/user/service/user-admin.service.ts
  src/modules/user/service/user-base.service.ts
  src/modules/user/service/user.service.ts
  src/modules/user/user-base.module.ts
  src/modules/user/user.module.ts
Labels: enhancement

#51 fix: 조회에 권한이 필요 없도록 수정
  src/modules/part/controller/part.controller.ts
Labels: bug

#52 조회에 권한이 필요 없도록 버그 수정
  src/modules/part/controller/part.controller.ts
Labels: bug

#53 Feature/portfolio
  src/modules/portfolio/controller/portfolio.controller.ts
  src/modules/portfolio/repository/portfolio.repository.ts
  src/modules/portfolio/service/portfolio.service.ts
Labels: invalid

#54 Feat/application transaction 까지 저장
  src/modules/application/application.module.ts
  src/modules/auth/role/rolesType.ts
  src/modules/generation/service/generation.service.ts
  src/modules/part/part-base.module.ts
  src/modules/part/service/part-base.service.ts
  src/modules/question/dto/create-question.dto.ts
  src/modules/question/dto/get-questions.dto.ts
  src/modules/question/service/question.service.ts
  src/modules/user/controller/user.controller.ts
  src/modules/user/service/user-admin.service.ts
  src/modules/user/service/user-base.service.ts
  src/modules/user/service/user.service.ts
Labels: enhancement

#55 Feat/application 임시 swagger 추가 배포
  src/infra/entity/Applications.entity.ts
  src/modules/application/application-base.module.ts
  src/modules/application/application.module.ts
  src/modules/application/controller/application.controller.ts
  src/modules/application/repository/answer.repository.ts
  src/modules/application/service/application-base.service.ts
  src/modules/application/service/application.service.ts
  src/modules/generation/service/generation.service.ts
  src/modules/part/controller/part.controller.ts
Labels: enhancement

#57 feat: 타입 오류 수정// todo: 타입만 수정한 버전
  src/modules/application/service/application-base.service.ts
  src/modules/application/service/application.service.ts
Labels: documentation

#59 feat: status enum으로 관리
  src/infra/entity/Applications.entity.ts
  src/modules/application/dto/create-application.dto.ts
  src/modules/application/service/application-base.service.ts
Labels: documentation

#60 enum관리 배포
  src/infra/entity/Applications.entity.ts
  src/modules/application/dto/create-application.dto.ts
  src/modules/application/service/application-base.service.ts
Labels: documentation

#61 Feat/application 임시 dto 추가
  src/modules/application/controller/application.controller.ts
  src/modules/application/dto/create-application.dto.ts
  src/modules/application/dto/update-application.dto.ts
  src/modules/application/service/application-base.service.ts
  src/modules/application/service/application.service.ts
  src/modules/part/service/part-base.service.ts
  src/modules/user/service/user-base.service.ts
Labels: documentation

#62 feat(User): user쪽에서 유저에 모든 지원서 가져오는 기능 추가
  src/modules/user/controller/user.controller.ts
  src/modules/user/service/user-admin.service.ts
  src/modules/user/service/user.service.ts
Labels: enhancement

#64 feat: transaction 을 공통 모듈로 분리
  src/modules/application/service/application.service.ts
  src/modules/common/common.module.ts
  src/modules/common/common.service.ts
  src/modules/question/service/question.service.ts
Labels: enhancement

#63 배포
  src/modules/application/controller/application.controller.ts
  src/modules/application/dto/create-application.dto.ts
  src/modules/application/dto/update-application.dto.ts
  src/modules/application/service/application-base.service.ts
  src/modules/application/service/application.service.ts
  src/modules/common/common.module.ts
  src/modules/common/common.service.ts
  src/modules/part/service/part-base.service.ts
  src/modules/question/service/question.service.ts
  src/modules/user/controller/user.controller.ts
  src/modules/user/service/user-admin.service.ts
  src/modules/user/service/user-base.service.ts
  src/modules/user/service/user.service.ts
Labels: documentation, enhancement

#65 Feat/application 지원 기능 완료
  src/infra/entity/Applications.entity.ts
  src/modules/application/controller/application.controller.ts
  src/modules/application/dto/update-application.dto.ts
  src/modules/application/service/application-admin.service.ts
  src/modules/application/service/application-base.service.ts
  src/modules/application/service/application.service.ts
  src/modules/common/common.service.ts
Labels: documentation, enhancement
